### PR TITLE
Order class terms chronologically in Distribution dropdown

### LINKED ISSUE #8: wrong term order
summer should be at the end

https://grades.natecation.xyz/STATS/100A

Screenshot 2023-07-14 at 08 14 21

### PR DESCRIPTION
**Pull request by TomBinford**
Closes #8

### CODE REVIEW

**Comment by TomBinford** [comment]
https://grades-natecation-xyz-git-fork-tombinford-main-nathanhleung.vercel.app/STATS/100A

**Review by nathanhleung — APPROVED** [review]
Thanks, lgtm!

File: app/utils.ts [hunk 1]
```diff
@@ -195,6 +195,38 @@ export function getTermLongName(term: string) {
...
+  }
+  else if (yearA < yearB) {
+    return -1;
+  }
+  if (quarterIndexA === -1) {
+    return 1;
+  }
+  else if (quarterIndexB === -1)  {
+    return -1;
+  }
```
Comment (nathanhleung) [inline app/utils.ts:226]: Technically these can all be `if` statements (since we early `return`)
